### ISSUE TITLE
/root/study-air-hockey/src/study-2.cpp:39:10: fatal error: spline.h: No such file or directory

### ISSUE THREAD

**Issue by jimingda** [pattacini/study-air-hockey#3]
```
11:46 # make  
Consolidate compiler generated dependencies of target study-air-hockey-1
[ 50%] Built target study-air-hockey-1
[ 75%] Building CXX object CMakeFiles/study-air-hockey-2.dir/src/study-2.cpp.o
/root/study-air-hockey/src/study-2.cpp:39:10: fatal error: spline.h: No such file or directory
   39 | #include "spline.h"
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/study-air-hockey-2.dir/build.make:76: CMakeFiles/study-air-hockey-2.dir/src/study-2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:129: CMakeFiles/study-air-hockey-2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by pattacini** [comment]
> https://github.com/ttk592/spline Maybe i shoud clone the project above

Yes, this project makes use of this external header-only dependency you ought to just download.
As this project is configured to run on Gitpod, the CMake infrastructure expects to find the external dependency at the particular path `/workspace/spline` as per the following:

https://github.com/pattacini/study-air-hockey/blob/6c4128c0244b344f583e0a7ed8c35b9f97cc783a/CMakeLists.txt#L28

Hence, either you clone the repo at that same path, or modify the `CMakeLists.txt` accordingly.

**Comment by pattacini** [comment]
@MR-RAICAM
